image: python:2.7

before_script:
    # pip is sensitive to internet glitches
    - export PIP_DEFAULT_TIMEOUT=120

    - apt-get update
    - apt-get install -y libarchive-dev p7zip-full zip

.artifacts: &artifacts
    artifacts:
        name: "$CI_JOB_NAME"
        expire_in: 1 wk
        paths:
            - dist/*.whl
            - examples/*
            - tests/*

#### build

.buildjob: &buildjob
    stage: build
    <<: *artifacts
    script:
        - ls -la *
        - pip wheel -v -w dist $PIP_ARGS .
        - ls -la dist
        - find . -iname \*.whl | xargs unzip -l

.buildplatjob: &buildplatjob
    <<: *buildjob
    variables:
        PIP_ARGS: --build-option --plat-name --build-option $CI_JOB_NAME

testsrc:
    stage: build
    <<: *artifacts
    script:
        - pip install libarchive
        - python download_deps.py
        - ls -la examples
        - ls -la tests

purelib:
    <<: *buildjob

manylinux1_i686:
    <<: *buildplatjob

manylinux1_x86_64:
    <<: *buildplatjob

win32:
    <<: *buildplatjob

win_amd64:
    <<: *buildplatjob

macosx_10_11_x86_64:
    <<: *buildplatjob

##### test

.linuxtest: &linuxtest
    stage: test
    <<: *artifacts
    script:
        - apt-get install -y python python-pip
        - pip install clang --no-index --find-links file://$PWD/dist
        - python -m unittest discover

test_linux_x86_64:
    image: ubuntu:16.04
    <<: *linuxtest

test_linux_i386:
    image: ioft/i386-ubuntu:16.04
    <<: *linuxtest

.installtest: &installtest
    stage: test
    script:
        - pip install .

install_py2:
    image: python:2.7
    <<: *installtest

install_py3:
    image: python:3.5
    <<: *installtest

##### deploy

collect:
    stage: deploy
    <<: *artifacts
    script:
        - ls -l dist/*.whl
