image: python:2.7

before_script:
    # pip is sensitive to internet glitches
    - export PIP_DEFAULT_TIMEOUT=120

.artifacts: &artifacts
    artifacts:
        name: "$CI_JOB_NAME"
        expire_in: 1 wk
        paths:
            - dist/*.whl
            - examples/*
            - tests/*

#### build

.buildjob: &buildjob
    stage: build
    <<: *artifacts
    script:
        - apt-get update
        - apt-get install -y libarchive-dev p7zip-full zip
        - ls -la *
        - pip wheel -v -w dist $PIP_ARGS .
        - ls -la dist
        - find . -iname \*.whl | xargs unzip -l

.buildplatjob: &buildplatjob
    <<: *buildjob
    variables:
        PIP_ARGS: --build-option --plat-name --build-option $CI_JOB_NAME

purelib:
    <<: *buildjob

manylinux1_i686:
    <<: *buildplatjob

manylinux1_x86_64:
    <<: *buildplatjob

win32:
    <<: *buildplatjob

win_amd64:
    <<: *buildplatjob

macosx_10_11_x86_64:
    <<: *buildplatjob

##### test

.linuxtest: &linuxtest
    stage: test
    <<: *artifacts
    script:
        - apt-get update && apt-get install -y python python-pip
        - pip install dist/*$WHEEL_PLAT.whl
        - python -m unittest discover

test_linux_x86_64:
    image: ubuntu:16.04
    variables:
        WHEEL_PLAT: manylinux1_x86_64
    <<: *linuxtest

test_linux_i386:
    image: ioft/i386-ubuntu:16.04
    variables:
        WHEEL_PLAT: manylinux1_i686
    <<: *linuxtest

##### deploy

collect:
    stage: deploy
    <<: *artifacts
    script:
        - ls -l dist/*.whl
