language: c
os: osx
osx_image:
    - xcode9.3
    - xcode8.3
    - xcode7.3

script:
    - echo ARTIFACT_URL $ARTIFACT_URL
    - wget $ARTIFACT_URL -O artifacts.zip
    - unzip artifacts.zip
    - brew update
    - brew remove --force --ignore-dependencies python python@2
    - brew install python@2 python@3
    - pip2 install clang --user --no-index --find-links file://$PWD/dist
    - python2 -m unittest discover
    - pip3 install clang --user --no-index --find-links file://$PWD/dist
    - python3 -m unittest discover
